/**
 * Idempotent injection of stamp-specific guidance into AGENTS.md at the
 * repo root. The stamp section lives between two HTML-comment delimiters
 * so re-running `stamp bootstrap` / `stamp init` replaces the section in
 * place without disturbing any other content the user has added.
 *
 * Why AGENTS.md and not CLAUDE.md: AGENTS.md is the cross-tool convention
 * the open-source ecosystem is converging on; tools like Claude Code,
 * Cursor, Aider, and others read it. Projects that want Claude-specific
 * guidance can keep a CLAUDE.md alongside that points at AGENTS.md.
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export const STAMP_BEGIN = "<!-- stamp:begin (managed by stamp-cli — do not edit between markers) -->";
export const STAMP_END = "<!-- stamp:end -->";

/**
 * The stamp section body. Speaks to a future agent dropped into this repo
 * with no context — names the gate model, the canonical loop, and the
 * concrete things NOT to do that an agent would otherwise reach for.
 */
export const STAMP_AGENTS_SECTION = `## Stamp-protected repository — read before changing code

This repository is gated by [stamp-cli](https://github.com/OpenThinkAi/stamp-cli).
Direct commits to protected branches (typically \`main\`) **will be rejected by
the server-side pre-receive hook**, even with valid credentials. Every change
to a protected branch must be a \`stamp merge\` signed locally and pushed via
\`stamp push\`.

### The canonical workflow

\`\`\`sh
git checkout -b feature
# ...edit, commit, repeat...

stamp review --diff main..feature       # all configured reviewers run in parallel
stamp status --diff main..feature       # exit 0 if every required reviewer approved

# When green:
git checkout main
stamp merge feature --into main         # signs an Ed25519 attestation into the merge trailer
stamp push main                         # server hook verifies; main advances on the remote
\`\`\`

If a reviewer returns \`changes_requested\`, read its prose in the \`stamp review\`
output (or via \`stamp log --reviews --limit 1\`), fix the code, commit, and
re-review. Verdicts are bound to the exact \`(base_sha, head_sha)\` pair, so a
new commit invalidates prior approvals.

### What NOT to do

- **Do not** \`git push origin main\` directly — bypasses the gate; will be rejected.
- **Do not** commit to \`main\` directly — same.
- **Do not** use \`--no-verify\` to skip hooks. Investigate hook failures, don't bypass them.
- **Do not** edit \`.stamp/config.yml\` or \`.stamp/reviewers/*.md\` casually — those changes
  go through the same reviewer gate as any other code change. Treat them as security-sensitive
  edits.
- **Do not** delete \`.stamp/trusted-keys/*.pub\` files unless you genuinely intend to revoke
  a signer; doing so locks that signer out of all future merges.

### Where things live

- \`.stamp/config.yml\` — branch rules (which reviewers are required, optional \`required_checks\`)
- \`.stamp/reviewers/*.md\` — reviewer prompt files; this is your project's review policy as code
- \`.stamp/trusted-keys/*.pub\` — Ed25519 public keys allowed to sign merges into protected branches
- \`~/.stamp/keys/ed25519{,.pub}\` — your local signing keypair (generated by \`stamp init\` /
  \`stamp keys generate\`; never committed)

### Useful commands

\`\`\`sh
stamp --help                              # full command list
stamp reviewers list                      # configured reviewers + prompt file status
stamp reviewers test <name> --diff <rev>  # iterate on a reviewer prompt without polluting the DB
stamp log                                 # recent stamped merges with attestation summaries
stamp verify <sha>                        # re-verify a specific merge commit's attestation
\`\`\`

### When stamp blocks you

See [\`docs/troubleshooting.md\`](./docs/troubleshooting.md) if it exists in this repo, or the
upstream copy at https://github.com/OpenThinkAi/stamp-cli/blob/main/docs/troubleshooting.md.
Common cases:

- \`gate CLOSED: missing approved verdicts\` — re-run \`stamp review\` (verdicts are SHA-bound;
  every new commit invalidates prior approvals)
- \`pre-merge checks failed\` — a \`required_check\` exited non-zero; the merge was rolled back
- \`remote: stamp-verify: rejecting refs/heads/main\` — server hook caught a bypass attempt
- \`required by rule but not defined\` — chicken-and-egg on a reviewer config change; see the
  troubleshooting entry, or use \`stamp bootstrap\` for the placeholder→real swap case
`;

/**
 * Insert or replace the stamp-managed section in an AGENTS.md body.
 *
 * - If `existing` already contains the delimiters, the content between them
 *   is replaced and everything outside is preserved verbatim.
 * - If `existing` lacks the delimiters but is non-empty, the stamp section
 *   is appended after a blank-line separator.
 * - If `existing` is empty/undefined, a complete AGENTS.md is generated
 *   with a brief preamble + the stamp section.
 *
 * Idempotent: calling injectStampSection on its own output is a no-op.
 */
export function injectStampSection(existing?: string): string {
  const stampBlock = `${STAMP_BEGIN}\n\n${STAMP_AGENTS_SECTION.trimEnd()}\n\n${STAMP_END}`;

  if (existing === undefined || existing.trim() === "") {
    return `# AGENTS.md

Guidance for AI agents working in this repository.

${stampBlock}
`;
  }

  const beginIdx = existing.indexOf(STAMP_BEGIN);
  const endIdx = existing.indexOf(STAMP_END);

  if (beginIdx !== -1 && endIdx !== -1 && endIdx > beginIdx) {
    // Replace the existing block in place. Splice from begin marker through
    // the end marker (inclusive of the END line itself).
    const before = existing.slice(0, beginIdx);
    const afterStart = endIdx + STAMP_END.length;
    const after = existing.slice(afterStart);
    return `${before}${stampBlock}${after}`;
  }

  // No markers present — append the block (with markers) after the existing
  // content. From the *next* run on, the markers will be there and the
  // replace-in-place branch above takes over, so this path runs at most once
  // per file.
  return `${existing.trimEnd()}\n\n${stampBlock}\n`;
}

/**
 * Create or refresh the stamp-managed section of AGENTS.md at the repo root.
 *
 * Returns:
 *   "created"   — file did not exist; wrote a fresh AGENTS.md
 *   "replaced"  — file existed with stamp markers; replaced the section in place
 *   "appended"  — file existed without stamp markers; appended a new block
 *   "unchanged" — file already contains the exact target content (no write)
 */
export function ensureAgentsMd(
  repoRoot: string,
): "created" | "replaced" | "appended" | "unchanged" {
  const path = join(repoRoot, "AGENTS.md");
  if (!existsSync(path)) {
    writeFileSync(path, injectStampSection(undefined));
    return "created";
  }
  const existing = readFileSync(path, "utf8");
  const updated = injectStampSection(existing);
  if (updated === existing) return "unchanged";
  const action = existing.includes(STAMP_BEGIN) ? "replaced" : "appended";
  writeFileSync(path, updated);
  return action;
}
